name = "HampelFilter"
uuid = "fe33c93a-55d1-4127-9154-6f3b36aa4321"
authors = ["Sorachi Kato"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
